### ISSUE TITLE
WE WANT A FLUENCY BUILDER SCRIPT 

### ISSUE THREAD

**Issue by s11dkl** [CheeseDanish1/Rosetta-Stone-Script#35]
PLEAAAAAAAAAAAASE

**Comment by ID-star-hue** [comment]
I already tried to make one but it's almost impossible , the **mutations** needed for influencing the fluency builder GraphQL are hidden and it's so difficult to find them , i tried contacting the rosetta stone support in order to take them but it turned out that i have to be working with them to access these mutations, cuz otherwise i'd be violationg their policies, if you guys know a way to convince them into giving me those mutations , then consider the script is completed...
![Capture d'écran 2024-12-08 142331](https://github.com/user-attachments/assets/61c23cc2-e08e-4a68-9d6d-40a4cb41ac7e)

**Comment by yahya219737737** [comment]
i think u cant convince them to give u sensible information like that

**Comment by ID-star-hue** [comment]
> i think u cant convince them to give u sensible information like that

then we're cooked asat

**Comment by yahya219737737** [comment]
Kifach mol had script ta7 3liha asln?

**Comment by ID-star-hue** [comment]
> Kifach mol had script ta7 3liha asln?

chkoun 3ref chi chat gpt o chwiya d knowledge f JS o html o css o cyber

**Comment by ommmmmmarrr** [comment]
salam wach 9aditoh script

**Comment by yahya219737737** [comment]
Chof hadi li l9it wach fiha dakchi li kt9lb 3lih
https://gist.github.com/besentv/c62f69f2df51bb2aa3f484d6e62dce1d?permalink_comment_id=5061495

**Comment by arifnegh45** [comment]
For fluency builder i have developed a script, i can give yall the hours and complete units as long as a question doesnt have multiple steps, french has a lot of questions with multiple steps which my script cant complete yet, english almost has no questions with multiple steps so i can complete units easily completly. for french only partly. add me on discord arifnegh45

**Comment by ID-star-hue** [comment]
> For fluency builder i have developed a script, i can give yall the hours and complete units as long as a question doesnt have multiple steps, french has a lot of questions with multiple steps which my script cant complete yet, english almost has no questions with multiple steps so i can complete units easily completly. for french only partly. add me on discord arifnegh45

Bro can u give me the script, I'll try to update it to be able to complete the questions with multiple steps that you mentioned, Dm me on discord ( sohaib9237 )
